// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MameCome
{
	public partial class WindowController : NSWindowController
	{
		public WindowController (IntPtr handle) : base (handle)
        {
		}

        public override void WindowDidLoad()
        {
            //透過のやり方、Load後じゃないと無理っぽい
            base.WindowDidLoad();
            base.Window.IsOpaque = false;
            base.Window.HasShadow = false;
            base.Window.BackgroundColor= NSColor.FromRgba(1, 1, 1, 0);
        }
    }
}
