// This file has been autogenerated from a class added in the UI designer.
//Mac固有ロジック
using System;

using Foundation;
using AppKit;
using CoreGraphics;

namespace MameComment
{
	public partial class BoardCommentView : NSView
	{

        public BoardCommentView (IntPtr handle) : base (handle)
		{

		}
        public void ChangeBgColor(CoreGraphics.CGColor ColorData){
            base.Layer.BackgroundColor = ColorData;
        }

        public CoreGraphics.CGColor GetBgColor(){
            return base.Layer.BackgroundColor;
        }
    }
}
