//MAC固有ロジック
// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MameComment
{
	public partial class MainWindowController : NSWindowController
	{
		public MainWindowController (IntPtr handle) : base (handle)
		{
		}
	}
}
