// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MameComment
{
	public partial class SettingWindowController : NSWindowController
	{
		public SettingWindowController (IntPtr handle) : base (handle)
		{
		}
	}
}
